# LANGUAGE message translation file for plpython
# Copyright (C) 2009-2022 PostgreSQL Global Development Group
# This file is distributed under the same license as the plpython (PostgreSQL) package.
#
# Use these quotes: « %s »
#
# Guillaume Lelarge <guillaume@lelarge.info>, 2009-2022.
#
msgid ""
msgstr ""
"Project-Id-Version: PostgreSQL 15\n"
"Report-Msgid-Bugs-To: pgsql-bugs@lists.postgresql.org\n"
"POT-Creation-Date: 2023-05-05 17:08+0000\n"
"PO-Revision-Date: 2024-09-16 16:35+0200\n"
"Last-Translator: Guillaume Lelarge <guillaume@lelarge.info>\n"
"Language-Team: French <guillaume@lelarge.info>\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"X-Generator: Poedit 3.5\n"

#: plpy_cursorobject.c:72
#, c-format
msgid "plpy.cursor expected a query or a plan"
msgstr "plpy.cursor attendait une requête ou un plan"

#: plpy_cursorobject.c:155
#, c-format
msgid "plpy.cursor takes a sequence as its second argument"
msgstr "plpy.cursor prends une séquence dans son second argument"

#: plpy_cursorobject.c:171 plpy_spi.c:205
#, c-format
msgid "could not execute plan"
msgstr "n'a pas pu exécuter le plan"

#: plpy_cursorobject.c:174 plpy_spi.c:208
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Séquence attendue de %d argument, %d obtenu : %s"
msgstr[1] "Séquence attendue de %d arguments, %d obtenus : %s"

#: plpy_cursorobject.c:321
#, c-format
msgid "iterating a closed cursor"
msgstr "itération d'un curseur fermé"

#: plpy_cursorobject.c:329 plpy_cursorobject.c:395
#, c-format
msgid "iterating a cursor in an aborted subtransaction"
msgstr "itération d'un curseur dans une sous-transaction annulée"

#: plpy_cursorobject.c:387
#, c-format
msgid "fetch from a closed cursor"
msgstr "récupérer à partir d'un curseur fermé"

#: plpy_cursorobject.c:430 plpy_spi.c:401
#, c-format
msgid "query result has too many rows to fit in a Python list"
msgstr "le résultat de la requête contient trop de lignes pour être intégré dans une liste Python"

#: plpy_cursorobject.c:482
#, c-format
msgid "closing a cursor in an aborted subtransaction"
msgstr "fermeture d'un curseur dans une sous-transaction annulée"

#: plpy_elog.c:125 plpy_elog.c:126 plpy_plpymodule.c:530
#, c-format
msgid "%s"
msgstr "%s"

#: plpy_exec.c:139
#, c-format
msgid "unsupported set function return mode"
msgstr "mode de retour non supporté pour la fonction SET"

#: plpy_exec.c:140
#, c-format
msgid "PL/Python set-returning functions only support returning one value per call."
msgstr ""
"les fonctions PL/python renvoyant des ensembles supportent seulement une\n"
"valeur renvoyée par appel."

#: plpy_exec.c:153
#, c-format
msgid "returned object cannot be iterated"
msgstr "l'objet renvoyé ne supporte pas les itérations"

#: plpy_exec.c:154
#, c-format
msgid "PL/Python set-returning functions must return an iterable object."
msgstr ""
"les fonctions PL/python renvoyant des ensembles doivent renvoyer un objet\n"
"itérable"

#: plpy_exec.c:168
#, c-format
msgid "error fetching next item from iterator"
msgstr "erreur lors de la récupération du prochain élément de l'itérateur"

#: plpy_exec.c:211
#, c-format
msgid "PL/Python procedure did not return None"
msgstr "la procédure PL/python n'a pas renvoyé None"

#: plpy_exec.c:215
#, c-format
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "la fonction PL/python avec un code de retour « void » ne renvoyait pas None"

#: plpy_exec.c:369 plpy_exec.c:395
#, c-format
msgid "unexpected return value from trigger procedure"
msgstr "valeur de retour inattendue de la procédure trigger"

#: plpy_exec.c:370
#, c-format
msgid "Expected None or a string."
msgstr "Attendait None ou une chaîne de caractères."

#: plpy_exec.c:385
#, c-format
msgid "PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr ""
"la fonction trigger PL/python a renvoyé « MODIFY » dans un trigger DELETE\n"
"-- ignoré"

#: plpy_exec.c:396
#, c-format
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Attendait None, « OK », « SKIP » ou « MODIFY »."

#: plpy_exec.c:446
#, c-format
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "échec de PyList_SetItem() lors de l'initialisation des arguments"

#: plpy_exec.c:450
#, c-format
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "échec de PyDict_SetItemString() lors de l'initialisation des arguments"

#: plpy_exec.c:462
#, c-format
msgid "function returning record called in context that cannot accept type record"
msgstr ""
"fonction renvoyant le type record appelée dans un contexte qui ne peut pas\n"
"accepter le type record"

#: plpy_exec.c:679
#, c-format
msgid "while creating return value"
msgstr "lors de la création de la valeur de retour"

#: plpy_exec.c:926
#, c-format
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] supprimé, ne peut pas modifier la ligne"

#: plpy_exec.c:931
#, c-format
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] n'est pas un dictionnaire"

#: plpy_exec.c:956
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "la clé TD[\"new\"] à la position ordinale %d n'est pas une chaîne"

#: plpy_exec.c:963
#, c-format
msgid "key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering row"
msgstr ""
"la clé « %s » trouvée dans TD[\"new\"]  n'existe pas comme colonne\n"
"de la ligne impactée par le trigger"

#: plpy_exec.c:968
#, c-format
msgid "cannot set system attribute \"%s\""
msgstr "ne peut pas initialiser l'attribut système « %s »"

#: plpy_exec.c:973
#, c-format
msgid "cannot set generated column \"%s\""
msgstr "ne peut pas initialiser la colonne générée « %s »"

#: plpy_exec.c:1031
#, c-format
msgid "while modifying trigger row"
msgstr "lors de la modification de la ligne du trigger"

#: plpy_exec.c:1089
#, c-format
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr "annulation forcée d'une sous-transaction qui n'a jamais été quittée"

#: plpy_main.c:111
#, c-format
msgid "multiple Python libraries are present in session"
msgstr "plusieurs bibliothèques Python sont présentes dans la session"

#: plpy_main.c:112
#, c-format
msgid "Only one Python major version can be used in one session."
msgstr "Seule une version majeure de Python peut être utilisée dans une session."

#: plpy_main.c:124
#, c-format
msgid "untrapped error in initialization"
msgstr "erreur non récupérée dans l'initialisation"

#: plpy_main.c:147
#, c-format
msgid "could not import \"__main__\" module"
msgstr "n'a pas pu importer le module « __main__ »"

#: plpy_main.c:156
#, c-format
msgid "could not initialize globals"
msgstr "n'a pas pu initialiser les variables globales"

#: plpy_main.c:354
#, c-format
msgid "PL/Python procedure \"%s\""
msgstr "procédure PL/python « %s »"

#: plpy_main.c:357
#, c-format
msgid "PL/Python function \"%s\""
msgstr "fonction PL/python « %s »"

#: plpy_main.c:365
#, c-format
msgid "PL/Python anonymous code block"
msgstr "bloc de code PL/Python anonyme"

#: plpy_plpymodule.c:168 plpy_plpymodule.c:171
#, c-format
msgid "could not import \"plpy\" module"
msgstr "n'a pas pu importer le module « plpy »"

#: plpy_plpymodule.c:182
#, c-format
msgid "could not create the spiexceptions module"
msgstr "n'a pas pu créer le module « spiexceptions »"

#: plpy_plpymodule.c:190
#, c-format
msgid "could not add the spiexceptions module"
msgstr "n'a pas pu ajouter le module « spiexceptions »"

#: plpy_plpymodule.c:257
#, c-format
msgid "could not generate SPI exceptions"
msgstr "n'a pas pu générer les exceptions SPI"

#: plpy_plpymodule.c:425
#, c-format
msgid "could not unpack arguments in plpy.elog"
msgstr "n'a pas pu déballer les arguments dans plpy.elog"

#: plpy_plpymodule.c:434
msgid "could not parse error message in plpy.elog"
msgstr "n'a pas pu analyser le message d'erreur dans plpy.elog"

#: plpy_plpymodule.c:451
#, c-format
msgid "argument 'message' given by name and position"
msgstr "argument 'message' donné par nom et position"

#: plpy_plpymodule.c:478
#, c-format
msgid "'%s' is an invalid keyword argument for this function"
msgstr "'%s' est une argument mot-clé invalide pour cette fonction"

#: plpy_plpymodule.c:489 plpy_plpymodule.c:495
#, c-format
msgid "invalid SQLSTATE code"
msgstr "code SQLSTATE invalide"

#: plpy_procedure.c:225
#, c-format
msgid "trigger functions can only be called as triggers"
msgstr "les fonctions trigger peuvent seulement être appelées par des triggers"

#: plpy_procedure.c:229
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "les fonctions PL/python ne peuvent pas renvoyer le type %s"

#: plpy_procedure.c:307
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "les fonctions PL/python ne peuvent pas accepter le type %s"

#: plpy_procedure.c:397
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "n'a pas pu compiler la fonction PL/python « %s »"

#: plpy_procedure.c:400
#, c-format
msgid "could not compile anonymous PL/Python code block"
msgstr "n'a pas pu compiler le bloc de code anonyme PL/python"

#: plpy_resultobject.c:117 plpy_resultobject.c:143 plpy_resultobject.c:169
#, c-format
msgid "command did not produce a result set"
msgstr "la commande n'a pas fourni d'ensemble de résultats"

#: plpy_spi.c:56
#, c-format
msgid "second argument of plpy.prepare must be a sequence"
msgstr "le second argument de plpy.prepare doit être une séquence"

#: plpy_spi.c:98
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare : le nom du type sur la position ordinale %d n'est pas une chaîne"

#: plpy_spi.c:170
#, c-format
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.prepare attendait une requête ou un plan"

#: plpy_spi.c:189
#, c-format
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute prends une séquence dans son second argument"

#: plpy_spi.c:297
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "échec de SPI_execute_plan : %s"

#: plpy_spi.c:339
#, c-format
msgid "SPI_execute failed: %s"
msgstr "échec de SPI_execute : %s"

#: plpy_subxactobject.c:92
#, c-format
msgid "this subtransaction has already been entered"
msgstr "cette sous-transaction est en cours d'utilisation"

#: plpy_subxactobject.c:98 plpy_subxactobject.c:156
#, c-format
msgid "this subtransaction has already been exited"
msgstr "déjà sorti de cette sous-transaction"

#: plpy_subxactobject.c:150
#, c-format
msgid "this subtransaction has not been entered"
msgstr "cette sous-transaction n'a jamais été utilisée"

#: plpy_subxactobject.c:162
#, c-format
msgid "there is no subtransaction to exit from"
msgstr "il n'y a pas de transaction à quitter"

#: plpy_typeio.c:588
#, c-format
msgid "could not import a module for Decimal constructor"
msgstr "n'a pas pu importer un module pour le constructeur Decimal"

#: plpy_typeio.c:592
#, c-format
msgid "no Decimal attribute in module"
msgstr "pas d'attribut Decimal dans le module"

#: plpy_typeio.c:598
#, c-format
msgid "conversion from numeric to Decimal failed"
msgstr "échec de la conversion numeric vers Decimal"

#: plpy_typeio.c:912
#, c-format
msgid "could not create bytes representation of Python object"
msgstr "n'a pas pu créer une représentation octets de l'objet Python"

#: plpy_typeio.c:1049
#, c-format
msgid "could not create string representation of Python object"
msgstr "n'a pas pu créer une représentation chaîne de caractères de l'objet Python"

#: plpy_typeio.c:1060
#, c-format
msgid "could not convert Python object into cstring: Python string representation appears to contain null bytes"
msgstr "n'a pas pu convertir l'objet Python en cstring : la représentation de la chaîne Python contient des octets nuls"

#: plpy_typeio.c:1157
#, c-format
msgid "return value of function with array return type is not a Python sequence"
msgstr "la valeur de retour de la fonction de type tableau n'est pas une séquence Python"

#: plpy_typeio.c:1202
#, c-format
msgid "could not determine sequence length for function return value"
msgstr "n'a pas pu déterminer la longueur de la séquence pour la valeur de retour de la fonction"

#: plpy_typeio.c:1222 plpy_typeio.c:1237 plpy_typeio.c:1253
#, c-format
msgid "multidimensional arrays must have array expressions with matching dimensions"
msgstr ""
"les tableaux multidimensionnels doivent avoir des expressions de tableaux\n"
"avec les dimensions correspondantes"

#: plpy_typeio.c:1227
#, c-format
msgid "number of array dimensions exceeds the maximum allowed (%d)"
msgstr "le nombre de dimensions du tableau dépasse le maximum autorisé (%d)"

#: plpy_typeio.c:1329
#, c-format
msgid "malformed record literal: \"%s\""
msgstr "enregistrement littéral invalide : « %s »"

#: plpy_typeio.c:1330
#, c-format
msgid "Missing left parenthesis."
msgstr "Parenthèse gauche manquante."

#: plpy_typeio.c:1331 plpy_typeio.c:1532
#, c-format
msgid "To return a composite type in an array, return the composite type as a Python tuple, e.g., \"[('foo',)]\"."
msgstr "Pour renvoyer un type composite dans un tableau, renvoyez le type composite sous la forme d'un tuple Python, c'est-à-dire \"[('foo',)]\"."

#: plpy_typeio.c:1378
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "la clé « %s » introuvable dans la correspondance"

#: plpy_typeio.c:1379
#, c-format
msgid "To return null in a column, add the value None to the mapping with the key named after the column."
msgstr ""
"Pour renvoyer NULL dans une colonne, ajoutez la valeur None à la\n"
"correspondance de la clé nommée d'après la colonne."

#: plpy_typeio.c:1432
#, c-format
msgid "length of returned sequence did not match number of columns in row"
msgstr ""
"la longueur de la séquence renvoyée ne correspondait pas au nombre de\n"
"colonnes dans la ligne"

#: plpy_typeio.c:1530
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "l'attribut « %s » n'existe pas dans l'objet Python"

#: plpy_typeio.c:1533
#, c-format
msgid "To return null in a column, let the returned object have an attribute named after column with value None."
msgstr ""
"Pour renvoyer NULL dans une colonne, faites en sorte que l'objet renvoyé ait\n"
"un attribut nommé suivant la colonne de valeur None."

#: plpy_util.c:31
#, c-format
msgid "could not convert Python Unicode object to bytes"
msgstr "n'a pas pu convertir l'objet Unicode Python en octets"

#: plpy_util.c:37
#, c-format
msgid "could not extract bytes from encoded string"
msgstr "n'a pas pu extraire les octets de la chaîne encodée"
