msgid ""
msgstr ""
"Project-Id-Version: postgresql\n"
"Report-Msgid-Bugs-To: pgsql-bugs@lists.postgresql.org\n"
"POT-Creation-Date: 2022-08-12 10:38+0000\n"
"PO-Revision-Date: 2022-09-13 11:52\n"
"Last-Translator: \n"
"Language-Team: Ukrainian\n"
"Language: uk_UA\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=4; plural=((n%10==1 && n%100!=11) ? 0 : ((n%10 >= 2 && n%10 <=4 && (n%100 < 12 || n%100 > 14)) ? 1 : ((n%10 == 0 || (n%10 >= 5 && n%10 <=9)) || (n%100 >= 11 && n%100 <= 14)) ? 2 : 3));\n"
"X-Crowdin-Project: postgresql\n"
"X-Crowdin-Project-ID: 324573\n"
"X-Crowdin-Language: uk\n"
"X-Crowdin-File: /REL_15_STABLE/plpython.pot\n"
"X-Crowdin-File-ID: 884\n"

#: plpy_cursorobject.c:72
#, c-format
msgid "plpy.cursor expected a query or a plan"
msgstr "plpy.cursor очікував запит або план"

#: plpy_cursorobject.c:155
#, c-format
msgid "plpy.cursor takes a sequence as its second argument"
msgstr "plpy.сursor приймає як другий аргумент послідовність"

#: plpy_cursorobject.c:171 plpy_spi.c:205
#, c-format
msgid "could not execute plan"
msgstr "не вдалося виконати план"

#: plpy_cursorobject.c:174 plpy_spi.c:208
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Очікувалась послідовність %d аргументів, отримано %d: %s"
msgstr[1] "Очікувалась послідовність %d аргументів, отримано %d: %s"
msgstr[2] "Очікувалась послідовність %d аргументів, отримано %d: %s"
msgstr[3] "Очікувалась послідовність %d аргумента, отримано %d: %s"

#: plpy_cursorobject.c:321
#, c-format
msgid "iterating a closed cursor"
msgstr "ітерація закритого курсора"

#: plpy_cursorobject.c:329 plpy_cursorobject.c:395
#, c-format
msgid "iterating a cursor in an aborted subtransaction"
msgstr "ітерація курсора в перерваній субтранзакції"

#: plpy_cursorobject.c:387
#, c-format
msgid "fetch from a closed cursor"
msgstr "витяг з закритого курсору"

#: plpy_cursorobject.c:430 plpy_spi.c:401
#, c-format
msgid "query result has too many rows to fit in a Python list"
msgstr "результат запиту має забагато рядків для передачі у список Python"

#: plpy_cursorobject.c:482
#, c-format
msgid "closing a cursor in an aborted subtransaction"
msgstr "закриття курсора в перерваній транзакції"

#: plpy_elog.c:125 plpy_elog.c:126 plpy_plpymodule.c:530
#, c-format
msgid "%s"
msgstr "%s"

#: plpy_exec.c:139
#, c-format
msgid "unsupported set function return mode"
msgstr "режим не підтримується для функцій, що повертають набір"

#: plpy_exec.c:140
#, c-format
msgid "PL/Python set-returning functions only support returning one value per call."
msgstr "функції PL/Python підтримують лише одне значення на виклик, коли повертають набір."

#: plpy_exec.c:153
#, c-format
msgid "returned object cannot be iterated"
msgstr "повернутий об'єкт не підтримує ітерації"

#: plpy_exec.c:154
#, c-format
msgid "PL/Python set-returning functions must return an iterable object."
msgstr "функції PL/Python повинні повертати об'єкт з підтримкою ітерації, коли повертають набір."

#: plpy_exec.c:168
#, c-format
msgid "error fetching next item from iterator"
msgstr "помилка отримання наступного елемента від ітератора"

#: plpy_exec.c:211
#, c-format
msgid "PL/Python procedure did not return None"
msgstr "процедура PL/Python не повернула None"

#: plpy_exec.c:215
#, c-format
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "PL/Python функція з типом результату \"void\" не повернули None"

#: plpy_exec.c:369 plpy_exec.c:395
#, c-format
msgid "unexpected return value from trigger procedure"
msgstr "неочікуване значення процедури тригера"

#: plpy_exec.c:370
#, c-format
msgid "Expected None or a string."
msgstr "Очікувалось None або рядок."

#: plpy_exec.c:385
#, c-format
msgid "PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr "Тригерна функція PL/Python повернула \"MODIFY\" в тригері DELETE -- проігноровано"

#: plpy_exec.c:396
#, c-format
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Очікувалось None, \"OK\", \"SKIP\" або \"MODIFY\"."

#: plpy_exec.c:441
#, c-format
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "помилка PyList_SetItem() під час встановлення параметрів"

#: plpy_exec.c:445
#, c-format
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "помилка PyDict_SetItemString() під час встановлення параметрів"

#: plpy_exec.c:457
#, c-format
msgid "function returning record called in context that cannot accept type record"
msgstr "функція, що повертає набір, викликана у контексті, що не приймає тип запис"

#: plpy_exec.c:674
#, c-format
msgid "while creating return value"
msgstr "під час створення значення результату"

#: plpy_exec.c:908
#, c-format
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] видалено, неможливо змінити рядок"

#: plpy_exec.c:913
#, c-format
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] не є словником"

#: plpy_exec.c:938
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "ключ словника TD[\"new\"] на порядковий позиції %d не є рядком"

#: plpy_exec.c:945
#, c-format
msgid "key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering row"
msgstr "ключ \"%s\" знайдений у TD[\"new\"] не існує як стовпець у рядку тригера"

#: plpy_exec.c:950
#, c-format
msgid "cannot set system attribute \"%s\""
msgstr "не вдалося встановити системний атрибут \"%s\""

#: plpy_exec.c:955
#, c-format
msgid "cannot set generated column \"%s\""
msgstr "неможливо оновити згенерований стовпець \"%s\""

#: plpy_exec.c:1013
#, c-format
msgid "while modifying trigger row"
msgstr "під час зміни рядка тригера"

#: plpy_exec.c:1071
#, c-format
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr "примусове переривання субтранзакції, яка не вийшла"

#: plpy_main.c:111
#, c-format
msgid "multiple Python libraries are present in session"
msgstr "декілька бібліотек Python присутні у сесії"

#: plpy_main.c:112
#, c-format
msgid "Only one Python major version can be used in one session."
msgstr "За один сеанс може використовуватися лише одна основна версія Python."

#: plpy_main.c:124
#, c-format
msgid "untrapped error in initialization"
msgstr "неопрацьована помилка під час ініціалізації"

#: plpy_main.c:147
#, c-format
msgid "could not import \"__main__\" module"
msgstr "не вдалося імпортувати \"__main__\" модуль"

#: plpy_main.c:156
#, c-format
msgid "could not initialize globals"
msgstr "не вдалося ініціалізувати globals"

#: plpy_main.c:354
#, c-format
msgid "PL/Python procedure \"%s\""
msgstr "PL/Python процедура \"%s\""

#: plpy_main.c:357
#, c-format
msgid "PL/Python function \"%s\""
msgstr "PL/Python функція \"%s\""

#: plpy_main.c:365
#, c-format
msgid "PL/Python anonymous code block"
msgstr "анонімні коди блоку PL/Python"

#: plpy_plpymodule.c:168 plpy_plpymodule.c:171
#, c-format
msgid "could not import \"plpy\" module"
msgstr "не вдалося імпортувати \"plpy\" модуль"

#: plpy_plpymodule.c:182
#, c-format
msgid "could not create the spiexceptions module"
msgstr "не вдалося створити spiexceptions модуль"

#: plpy_plpymodule.c:190
#, c-format
msgid "could not add the spiexceptions module"
msgstr "не вдалося додати spiexceptions модуль"

#: plpy_plpymodule.c:257
#, c-format
msgid "could not generate SPI exceptions"
msgstr "не вдається створити винятки SPI"

#: plpy_plpymodule.c:425
#, c-format
msgid "could not unpack arguments in plpy.elog"
msgstr "не вдалося розпакувати аргументи в plpy.elog"

#: plpy_plpymodule.c:434
msgid "could not parse error message in plpy.elog"
msgstr "не вдалося проаналізувати повідомлення про помилку в plpy.elog"

#: plpy_plpymodule.c:451
#, c-format
msgid "argument 'message' given by name and position"
msgstr "аргумент 'повідомлення' виданий за ім'ям та розташуванням"

#: plpy_plpymodule.c:478
#, c-format
msgid "'%s' is an invalid keyword argument for this function"
msgstr "'%s' є неприпустимим ключовим словом-аргументом для цієї функції"

#: plpy_plpymodule.c:489 plpy_plpymodule.c:495
#, c-format
msgid "invalid SQLSTATE code"
msgstr "неприпустимий код SQLSTATE"

#: plpy_procedure.c:225
#, c-format
msgid "trigger functions can only be called as triggers"
msgstr "тригер-функція може викликатися лише як тригер"

#: plpy_procedure.c:229
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "PL/Python функції не можуть повернути тип %s"

#: plpy_procedure.c:307
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "PL/Python функції не можуть прийняти тип %s"

#: plpy_procedure.c:397
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "не вдалося скомпілювати функцію PL/Python \"%s\""

#: plpy_procedure.c:400
#, c-format
msgid "could not compile anonymous PL/Python code block"
msgstr "не вдалося скомпілювати анонімні коди блоку PL/Python"

#: plpy_resultobject.c:117 plpy_resultobject.c:143 plpy_resultobject.c:169
#, c-format
msgid "command did not produce a result set"
msgstr "команда не створила набір результатів"

#: plpy_spi.c:56
#, c-format
msgid "second argument of plpy.prepare must be a sequence"
msgstr "другий аргумент plpy.prepare має бути послідовністю"

#: plpy_spi.c:98
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: ім'я на порядковий позиції %d не є рядком"

#: plpy_spi.c:170
#, c-format
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute очікував запит або план"

#: plpy_spi.c:189
#, c-format
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute приймає як другий аргумент послідовність"

#: plpy_spi.c:297
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "SPI_execute_plan не спрацював: %s"

#: plpy_spi.c:339
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute не спрацював: %s"

#: plpy_subxactobject.c:92
#, c-format
msgid "this subtransaction has already been entered"
msgstr "ця субтранзакція вже почалась"

#: plpy_subxactobject.c:98 plpy_subxactobject.c:156
#, c-format
msgid "this subtransaction has already been exited"
msgstr "ця субтранзакція вже вийшла"

#: plpy_subxactobject.c:150
#, c-format
msgid "this subtransaction has not been entered"
msgstr "ця субтранзакція ще не почалася"

#: plpy_subxactobject.c:162
#, c-format
msgid "there is no subtransaction to exit from"
msgstr "немає субтранзакції, щоб з неї вийти"

#: plpy_typeio.c:587
#, c-format
msgid "could not import a module for Decimal constructor"
msgstr "не вдалося імпортувати модуль для конструктора Decimal"

#: plpy_typeio.c:591
#, c-format
msgid "no Decimal attribute in module"
msgstr "відсутній атрибут Decimal у модулі"

#: plpy_typeio.c:597
#, c-format
msgid "conversion from numeric to Decimal failed"
msgstr "не вдалося виконати перетворення з numeric на Decimal"

#: plpy_typeio.c:911
#, c-format
msgid "could not create bytes representation of Python object"
msgstr "не вдалося створити байтову репрезентацію об'єкта Python"

#: plpy_typeio.c:1048
#, c-format
msgid "could not create string representation of Python object"
msgstr "не вдалося створити рядкову репрезентацію об'єкта Python"

#: plpy_typeio.c:1059
#, c-format
msgid "could not convert Python object into cstring: Python string representation appears to contain null bytes"
msgstr "не вдалося перетворити об'єкт Python на cstring: репрезентація рядка Python містить значення null-байти"

#: plpy_typeio.c:1170
#, c-format
msgid "number of array dimensions exceeds the maximum allowed (%d)"
msgstr "кількість вимірів масиву перевищує максимально дозволену (%d)"

#: plpy_typeio.c:1175
#, c-format
msgid "could not determine sequence length for function return value"
msgstr "не вдалося визначити довжину послідовності для значення функція"

#: plpy_typeio.c:1180 plpy_typeio.c:1186
#, c-format
msgid "array size exceeds the maximum allowed"
msgstr "розмір масиву перевищує максимально дозволений"

#: plpy_typeio.c:1214
#, c-format
msgid "return value of function with array return type is not a Python sequence"
msgstr "значення функції з масивом в якості результату не є послідовністю Python"

#: plpy_typeio.c:1261
#, c-format
msgid "wrong length of inner sequence: has length %d, but %d was expected"
msgstr "неправильна довжина внутрішньої послідовності: довжина %d, але очікується %d"

#: plpy_typeio.c:1263
#, c-format
msgid "To construct a multidimensional array, the inner sequences must all have the same length."
msgstr "Щоб побудувати багатовимірний масив, внутрішні послідовності повинні мати однакову довжину."

#: plpy_typeio.c:1342
#, c-format
msgid "malformed record literal: \"%s\""
msgstr "невірно сформований літерал запису: \"%s\""

#: plpy_typeio.c:1343
#, c-format
msgid "Missing left parenthesis."
msgstr "Відсутня ліва дужка."

#: plpy_typeio.c:1344 plpy_typeio.c:1545
#, c-format
msgid "To return a composite type in an array, return the composite type as a Python tuple, e.g., \"[('foo',)]\"."
msgstr "Щоб повернути складений тип в масиві, треба повернути композитний тип як кортеж Python, наприклад, \"[('foo',)]\"."

#: plpy_typeio.c:1391
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "ключ \"%s\" не знайдено в зіставленні"

#: plpy_typeio.c:1392
#, c-format
msgid "To return null in a column, add the value None to the mapping with the key named after the column."
msgstr "Для повернення значення null в стовпці, додайте значення None з ключом, що дорівнює імені стовпця."

#: plpy_typeio.c:1445
#, c-format
msgid "length of returned sequence did not match number of columns in row"
msgstr "довжина повернутої послідовності не відповідає кількості стовпців у рядку"

#: plpy_typeio.c:1543
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "атрибут \"%s\" не існує в об'єкті Python"

#: plpy_typeio.c:1546
#, c-format
msgid "To return null in a column, let the returned object have an attribute named after column with value None."
msgstr "Щоб повернути null в стовпці, результуючий об'єкт має мати атрибут з іменем стовпця зі значенням None."

#: plpy_util.c:31
#, c-format
msgid "could not convert Python Unicode object to bytes"
msgstr "не вдалося конвертувати об'єкт Python Unicode в байти"

#: plpy_util.c:37
#, c-format
msgid "could not extract bytes from encoded string"
msgstr "не можливо отримати байт з закодованого рядка"

